---
title: "ggplot2"
author: "Yining Zhang"
date: "7/6/2020"
output:
  html_document: default
  pdf_document: default
  word_document: default
---
Learn data visulization with 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(MASS)
library(conflicted)
conflict_prefer("select","dplyr")
```


```{r, message = F}
#National Parks in California
ca <- read_csv("D:\\R\\ca.csv") 

#Acadia National Park
acadia <- read_csv("D:\\R\\acadia.csv")

#Southeast US National Parks
se <- read_csv("D:\\R\\se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("D:\\R\\visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("D:\\R\\mass.csv")

```

```{r}
head(ca)
attach(ca)
ggplot(data = ca) + 
  geom_point(aes(x = year, y = visitors))

```

```{r}
ggplot(data = ca) +    
  geom_point(aes(x = year, y = visitors, color = park_name))
```

```{r}
ggplot(data = ca) +
    geom_point(aes(x = year, y = visitors, color = park_name)) +
    labs(x = "Year",
       y = "Visitation",
       title = "California National Park Visitation") +
    theme_bw() +
    theme(legend.title=element_blank())
```



```{r}
attach(se)

```

```{r}
ggplot(data = se) +
    geom_point(aes(x = year, y = visitors)) +
    facet_wrap(~ state)
```

```{r}
ggplot(data = se) +
     geom_point(aes(x = year, y = visitors, color = park_name)) +
     facet_wrap(~ state, scales = "free")
```

```{r}
ggplot(data = se) + 
  geom_jitter(aes(x = park_name, y = visitors, color = park_name), 
              width = 0.1, 
              alpha = 0.2) +
  coord_flip() +
  theme(legend.position = "none")
```

```{r}
ggplot(se, aes(x = park_name, y = visitors)) +   
  geom_boxplot() +  
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
ggplot(se, aes(x = year, y = visitors, color = park_name)) +
   geom_line()
```



```{r}
ggplot(data = acadia) + 
  geom_point(aes(x = year, y = visitors)) +
  geom_line(aes(x = year, y = visitors)) +
  geom_smooth(aes(x = year, y = visitors),color = 'red') +
  labs(title = "Acadia National Park Visitation",
       y = "Visitation",
       x = "Year") +
  theme_bw()
```

```{r}
ggplot(data = acadia,aes(x = year, y = visitors)) + 
  geom_point() +
  geom_line() +
  geom_smooth(color = 'red') +
  labs(title = "Acadia National Park Visitation",
       y = "Visitation",
       x = "Year") +
  theme_bw()
```

```{r}
ggplot(data = visit_16, aes(x = state)) + 
  geom_bar()
```



```{r}
ggplot(data = visit_16, aes(x = state, y = visitors, fill = park_name)) + 
  geom_bar(stat = "identity")
```

```{r}
ggplot(data = visit_16, aes(x = state, y = visitors, fill = park_name)) + 
  geom_bar(stat = "identity", position = "dodge")
```

```{r}
pdf('D:\\R\\my_plot.pdf')
my_plot <- ggplot(data = mass) + 
      geom_bar(aes(x = type, fill = park_name)) +
  labs(x = "", y = "")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 7))
# ggsave("name_of_file.png", my_plot, width = 15, height = 10)
dev.off()
```

